version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kahootz
      MYSQL_USER: kahootz
      MYSQL_PASSWORD: kahootz
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: kahootz
      WORDPRESS_DB_PASSWORD: kahootz
      WORDPRESS_DB_NAME: kahootz
    volumes:
      - ../:/var/www/html
    extra_hosts:
      - "downloads.wordpress.org:66.6.42.250"
      - "api.wordpress.org:66.6.42.251"

volumes:
  db_data:
